### ISSUE TITLE
Problen activing Qgis2Web in Qgis 3.0.3

### ISSUE THREAD

**Issue by nugaldea** [tomchadwin/web2qgis#21]
No se pudo cargar el complemento 'qgis2web' debido a un error al llamar a su método classFactory() 

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 30, in 
    from qgis2web.maindialog import MainDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 57, in 
    from qgis.PyQt.QtWebKitWidgets import QWebView, QWebInspector, QWebPage
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtWebKitWidgets.py", line 26, in 
    from PyQt5.QtWebKitWidgets import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

Versión de Python: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
Versión de QGIS: 3.0.3-Girona Girona, 8a899c8 

Ruta de Python:
/usr/share/qgis/python
/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python
/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/nugaldea/.local/share/QGIS/QGIS3/profiles/default/python
/home/nugaldea/Descargas/Mapa Prueba

**Comment by tomchadwin** [comment]
Your environment is missing the Python bindings for QtWebkit. Try this (or the equivalent for your distro):

```bash
apt-get -y install python3-pyqt5.qtwebkit libqt5webkit5-dev
```

**Comment by tomchadwin** [comment]
By the way, this is the repository for web2qgis, not qgis2web. Try here instead:

https://github.com/tomchadwin/qgis2web/

**Comment by Jimmy16b** [comment]
![Captura de pantalla 2020-10-02 a las 15 15 38](https://user-images.githubusercontent.com/72261921/94927119-240e1000-04c2-11eb-93e7-c30370067e19.png)
Buenas tengo un problema parecido, estoy intentando instalar un complemento para realizar un practica pero siempre me sale este error, uso la versión de QGIS 3.4.10 y tengo un Mac
