### ISSUE TITLE
TypeError:  'NonType Object is not iterable'

### ISSUE THREAD

**Issue by leoouma** [tomchadwin/web2qgis#22]
This[ test page](http://leoouma.github.io/KETRACO_LINES/index.html) returns:

An error has occurred while executing Python code: 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/leonard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\web2qgis\web2qgis_dialog.py", line 91, in getMap
    getOpenlayersMap(self.mainframe, self.iface)
  File "C:/Users/leonard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\web2qgis\openlayersReader.py", line 44, in getOpenlayersMap
    for count, lyr in enumerate(lyrs):
TypeError: 'NoneType' object is not iterable

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.2-Bonn Bonn, 26842169e9 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/leonard/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/leonard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/leonard/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\leonard\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\leonard\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\leonard\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
.
http://leoouma.github.io/KETRACO_LINES/index.html

**Comment by tomchadwin** [comment]
The OpenLayers importer has had very little development, I'm afraid. The Leaflet importer has had a little more, but the whole plugin has not seen any work for a while, and I don't know whether I'll have much time to work on it. It's a pity, as I can see broadly how to take it further.
