### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' 

### ISSUE THREAD

**Issue by cbertelli** [tomchadwin/web2qgis#23]
Hello Tom,
thank you for the good idea and thanks a lot for the time spent on this plugin.
I found this issue on a leaflet map here:
https://www.laboratoriovalsusa.it/aziende
The map was correctly detected, but saving it, the plugin stopped with this error.
I'm probably not able to fix it by myself. Sorry.

````
 AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/Users/carlo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/web2qgis/web2qgis_dialog.py", line 87, in getMap
    getLeafletMap(self.mainframe, self.iface)
  File "/Users/carlo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/web2qgis/leafletReader.py", line 54, in getLeafletMap
    getLeafletView(scriptFolder, mainframe, iface)
  File "/Users/carlo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/web2qgis/leafletReader.py", line 59, in getLeafletView
    xMin, yMin, xMax, yMax = extent.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
````

**Comment by tomchadwin** [comment]
I don't get any error or imported map at all. Like you, it detects the map, but then when I click Save, I get nothing. Odd.

**Comment by mnoorchenar** [comment]
I have the same problem!
